name: clean_code_architecture
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  connectivity_plus: ^1.4.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  http: ^0.13.0
  shared_preferences: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  

flutter:
  uses-material-design: true
